/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#cecdff",
        "surface": "#f5f6f7",
        "primary-dim": "#0040cb",
        "on-surface-variant": "#595c5d",
        "on-error": "#ffefef",
        "inverse-on-surface": "#9b9d9e",
        "secondary": "#4e4fb6",
        "outline-variant": "#abadae",
        "on-secondary-container": "#3939a1",
        "on-primary": "#f2f1ff",
        "tertiary": "#903985",
        "on-tertiary-fixed": "#41003d",
        "tertiary-container": "#fc96e9",
        "on-secondary-fixed": "#24228d",
        "primary": "#0049e6",
        "on-tertiary": "#ffeef7",
        "surface-dim": "#d1d5d7",
        "on-tertiary-fixed-variant": "#6e1966",
        "on-primary-fixed-variant": "#002278",
        "outline": "#757778",
        "surface-bright": "#f5f6f7",
        "surface-container-high": "#e0e3e4",
        "surface-tint": "#0049e6",
        "on-secondary-fixed-variant": "#4343ab",
        "on-surface": "#2c2f30",
        "inverse-primary": "#6a89ff",
        "surface-variant": "#dadddf",
        "on-primary-fixed": "#000000",
        "error": "#b41340",
        "inverse-surface": "#0c0f10",
        "secondary-dim": "#4242aa",
        "primary-fixed": "#829bff",
        "secondary-fixed-dim": "#bebeff",
        "secondary-fixed": "#cecdff",
        "tertiary-fixed": "#fc96e9",
        "on-error-container": "#510017",
        "on-primary-container": "#001a63",
        "surface-container-highest": "#dadddf",
        "error-dim": "#a70138",
        "on-background": "#2c2f30",
        "on-secondary": "#f4f1ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#822c78",
        "primary-container": "#829bff",
        "on-tertiary-container": "#640d5d",
        "error-container": "#f74b6d",
        "surface-container": "#e6e8ea",
        "primary-fixed-dim": "#6e8cff",
        "background": "#f5f6f7",
        "surface-container-low": "#eff1f2",
        "tertiary-fixed-dim": "#ec89da"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}